name: CI/CD Pipeline

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Message
        run: echo "CI berhasil dijalankan"

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Staging
        run: echo "Deployment ke staging berhasil"